name: Test and deploy

on: [ push ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  build:
    needs: [ laravel-tests ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies
        run: npm install
      - name: Build assets
        run: npm run production
      - name: Clean directories
        run: |
          rm -Rf node_modules
          rm -Rf vendor
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/node_modules/"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_NAME=gacek
          envkey_APP_ENV=production
          envkey_APP_KEY=base64:xt2G6AYqwEQIOS5P8T6waIGU8bJq9xcvl98v+JZuCrg=
          envkey_APP_DEBUG=true
          envkey_APP_URL=https://gackowski.edu.pl
          envkey_LOG_CHANNEL=stack
          envkey_BROADCAST_DRIVER=log
          envkey_CACHE_DRIVER=file
          envkey_QUEUE_CONNECTION=sync
          envkey_SESSION_DRIVER=file
          envkey_SESSION_LIFETIME=120
          envkey_MAIL_MAILER=smtp
          envkey_MAIL_HOST=smtp.zenbox.pl
          envkey_MAIL_PORT=587
          envkey_MAIL_USERNAME=biuro@gackowski.edu.pl
          envkey_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          envkey_MAIL_ENCRYPTION=tls
          envkey_MAIL_FROM_ADDRESS=biuro@gackowski.edu.pl
          envkey_MAIL_FROM_NAME="Biuro Gacka"
          envkey_WORDPRESS_URL=https://blog.gackowski.edu.pl
          envkey_DA_USERNAME=gacek
          envkey_DA_CLIENT_ID=15247
          envkey_DA_SECRET=2d9cc65251e07ad4d70d6c61ad138ae6
          file_name: .env

      - name: Composer and migrations
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.TARGET }}
            composer install
